# -*- coding: utf-8 -*-
"""OrleansStockExchange.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ofIc1uZsQJEZCKmS4y89PQtpMYclDwwt
"""

import random
money=1000
shares=0
stockprice=round(random.uniform(50,150),2)
change=float()
def buy(money,stockprice,shares):
  try:
    amount = int(input("How many shares would you like to buy?"))
  except ValueError:
    print("Needed to be an integer")
  while amount * stockprice > money:
    print("You don't have enough money to perform this transaction.")
    try:
      amount = int(input("How many shares would you like to buy?"))
    except ValueError:
      print("Needed to be an integer")
  money = money-(amount*stockprice)
  shares = shares + amount
  return money,shares
def sell(money,stockprice,shares):
  try:
    amount = int(input("How many shares would you like to sell?"))
  except ValueError:
    print("Needed to be an integer")
  while amount > shares:
    print("You don't have enough shares to perform this action")
    try:
      amount = int(input("How many shares would you like to sell?"))
    except ValueError:
      print("Needed to be an integer")
  money = money + (amount * stockprice)
  shares = shares - amount
  return money,shares

for i in range(10):
  print(f""">Current data<
Day: {i+1}
Money: {money}
Shares owned: {shares}
Shares price: {stockprice}""")
  choice=input("Buy, sell or hold?")
  while choice.lower() not in ["buy","sell","hold"]:
    choice=input("Enter buy, sell or hold: ")
  if choice.lower() == "buy":
    money,shares = buy(money,stockprice,shares)
    print(f""">Current data<
Day: {i+1}
Money: {money}
Shares owned: {shares}
Shares price: {stockprice}""")
  elif choice.lower() == "sell":
    money,shares = sell(money,stockprice,shares)
    print(f""">Current data<
Day: {i+1}
Money: {money}
Shares owned: {shares}
Shares price: {stockprice}""")
  elif choice.lower() == "hold":
    pass
  change=random.uniform(0.8,1.2)
  stockprice=stockprice*change
print(f"Profit = {money-1000}")